### PR TITLE
fix: during initialization, set animation time to 0

### LINKED ISSUE #47: Disabled dock shows on unlock
**Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
``` 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

I'm not positive that this is the correct package, but maybe?

```
gnome-shell-extension-cosmic-dock:
  Installed: 69ubuntu1pop0~1626711379~21.04~5384aa0
  Candidate: 69ubuntu1pop0~1626711379~21.04~5384aa0
  Version table:
 *** 69ubuntu1pop0~1626711379~21.04~5384aa0 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

With dock disabled (Settings → Desktop → Dock → "Enable Dock"), the dock still displays briefly before hiding after locking the session and then unlocking.

**Steps to reproduce (if you know):**

1. Disable dock (Settings → Desktop → Dock → "Enable Dock" switched off).
2. Lock the session with Super+Esc
3. Unlock by entering password. Note that dock briefly shows before hiding again.

**Expected behavior:**

With the dock disabled, I expect it to remain invisible on login/unlock.

### PR DESCRIPTION
**Pull request by pbui**
If manual hide is enabled, then we do not want to animate the dock at
all.  However, the _animateOut function performs some side-effects on
completion, so we need to run it... therefore just set the timeout to 0.

To distinguish between normal behavior and initialization, introduce a
boolean init variable to _updateDashMode and _updateDashVisibility that
by default is set to false and thus performs the old behavior.  In
_initialize, however, we call _updateDashMode with this parameter to
true and thus eliminate the animation time.

The outcome of this change is that unlocking the screen or reloading the
extension will not animate the dock if it is set to manual hide.

Fixes #47 and pop-os/cosmic:#145

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Review by jacobgkau — COMMENTED** [review]
Thank you for the contribution.

I cannot currently recreate https://github.com/pop-os/cosmic/issues/145.

This doesn't seem to entirely fix https://github.com/pop-os/cosmic-dock/issues/47. On a lemp10 (Intel graphics), I no longer see the dock itself after locking/unlocking, but I still see an empty space at the bottom of the screen, with the windows needing to resize themselves to fill in the space after every unlock.

Before:

https://user-images.githubusercontent.com/7199422/143943253-1e685635-73f7-427e-b49b-068da0e305bd.mp4

After:

https://user-images.githubusercontent.com/7199422/143943257-b36b5f0c-4d95-4001-9780-c86f6d29d1bf.mp4

For the issue to be truly fixed, we would want to not see that empty space at the bottom of the screen just after unlocking. Is this behavior different from what you're seeing?

**Comment by pbui** [comment]
Hmm.  Ok, I can reproduce that behavior if the **Dock Visibility** is set to **Always Visible**.  If you change it to the other two options, it will not have the resizing problem.

I could try to fix this in the extension (if manual_hide is active, then also change the visibility), but it might be better for the desktop-widget to change the visibilty when the user disables the Dock.

What do you think is the better solution?

**Comment by pbui** [comment]
Note, I have **Dock Visibility** set to **Intelligently Hide**, which is why I missed this.

**Comment by jacobgkau** [comment]
Ah, I see. Unlocking works as expected with the other two visibility modes.

> I could try to fix this in the extension (if manual_hide is active, then also change the visibility), but it might be better for the desktop-widget to change the visibilty when the user disables the Dock.

If "disabling the dock" is actually just enabling a `manual_hide` setting, then having desktop-widget change the visibility when disabling makes sense to me on the surface.

However, desktop-widget would then need to keep track of the old visibility setting and restore it when the dock is re-enabled, or else the visibility would be reset to either `Always hide` or `Intelligently hide` (neither of which is the default option) when it's re-enabled. Having the visibility change just by flipping the `Enable Dock` switch off and on would not be desirable; a user wouldn't expect that to persistently affect other settings, and it might look like the dock wasn't re-enabled as requested if it's then hidden.

Also, addressing this in desktop-widget's handling of changing the settings would not fix the visual glitch for users who already have `Enable Dock` flipped to off and `Dock Visibility` still set to `Always visible`. For this to be a proper solution, it would need to apply retroactively with the package update, or at least with the next release upgrade.

With those two points in mind, it seems like addressing this fully in cosmic-dock would be better than relying on desktop-widget at this point in time.

**Comment by pbui** [comment]
@jacobgkau I found a simple fix.  This should prevent the dock from being visible if `manualhide` is one.  I no longer get the resizing behavior when the visibility is set to **Always**.

Please let me know if this fixes it for you.

**Comment by pbui** [comment]
Arg... sorry, had some issues git amending... it should be up-to-date now.

File: docking.js [hunk 1]
```diff
@@ -405,7 +405,7 @@ var DockedDash = GObject.registerClass({
         if (Main.uiGroup.contains(global.top_window_group))
             Main.uiGroup.set_child_below_sibling(this, global.top_window_group);
 
-        if (settings.get_boolean('dock-fixed')) {
+        if (settings.get_boolean('dock-fixed') && !settings.get_boolean('manualhide')) {
```
Comment (pbui) [inline docking.js]: This keeps the user's visibility setting; it will just prevent the dock from being visible initially if `manualhide` is active.

This way we don't need to keep track of the visibility setting ourselves when the dock is disabled.

**Comment by jacobgkau** [comment]
On 1503032, the glitch is now gone when the dock is disabled. However, when re-enabling the dock, windows don't resize to get out of the way:

Screenshot from 2021-11-29 15-00-46

If I change visibility to either of the `hide` options and then back to `Always visible`, then the windows do get out of the way, and they continue to do so when toggling `Enable Dock` back and forth. I can recreate it again by disabling the dock while set to `Always visible`, restarting the shell, and enabling it again.

**Comment by pbui** [comment]
Hmm... Ok. I can reproduce that behavior as well.  Let me think on this a bit more and I'll see if I can find away around it.  

Thanks for the feedback.

**Comment by pbui** [comment]
@jacobgkau Ok, with the latest commits you should able to toggle the dock on and off with proper resizing behavior while fixing the main issue of keeping the dock hidden on screen unlock.

I incorporated some refactoring from upstream in regards to "dock-fixed" and then used the new functions to properly implement the **manualhide** toggle.

I did two commits to logically separate the changes, but I can rebase them into one commit if you wish.

Let me know if you run into any other problematic test cases.

**Comment by jacobgkau** [comment]
I'm currently seeing the dock show up if it's set to `Intelligently hide` and disabled (when I move the cursor to the bottom of the screen):

Screenshot from 2021-11-30 10-31-53

**Comment by jacobgkau** [comment]
Since this is taking some back-and-forth to get right (which is perfectly fine), I wanted to point out that `master_impish` has already been branched off for 21.10, which is very near release. It may be a better use of effort to solve the issues for that branch instead of `master_hirsute`; otherwise, someone will need to apply the improvements to `master_impish` separately once they're finished here.

`master_impish` seems to have the opposite problem from what this is solving, where the dock actually animates _in_ on every unlock when it's enabled rather than animating out when it's disabled.

**Comment by pbui** [comment]
Ok, I think the latest commit should fix it... I didn't really understand what the `.bind()` method was doing and after reading more about it, I can see now that it doesn't actually call the method (it mades a new one).  Now that we actually the method, the settings are updated and the Dock should behavior properly.

**Comment by pbui** [comment]
Regarding `master_impish`, I'd like for this to be resolved in `master_hirsute` first since that is what I am using.

That said, if I can run the `master_impish` branch on 21.04 (I do not want to use the beta yet), I'd be happy to look at that issue after this is resolved.  Otherwise, I may be able to try out the beta in two weeks and then look at the issues present in the new branch.

**Comment by jacobgkau** [comment]
On fd93117, when the dock is set to `Intelligently hide` and enabled, after I change the dock's position (bottom/left/right), I can't make it show with the cursor until I move between workspaces at least once.

**Comment by pbui** [comment]
Hmm... this only happens when "extend dock to the edges of the screen" is enabled... which I typically don't have.

If this is disabled, then it behaves properly. I'll have to think about this some more.

**Comment by pbui** [comment]
@jacobgkau Ok... I think I've fixed the issue with changing the dock's position (while keeping all the other edge cases working).  To do this, I only set the animation time to `0` for the `manualhide` mode during initialization. 🤞

**Comment by jacobgkau** [comment]
With the dock enabled but set to `Always hide` or `Intelligently hide`, the dock briefly appears when unlocking the screen before it's hidden. This visual glitch does not occur on the currently-released version.

**Comment by pbui** [comment]
I noticed that... I didn't remember if that was expected behavior or not.  I'll take another look.

**Comment by pbui** [comment]
The latest commit 5023582 separates animation in time from animation out time.  During initialization, always set the animation out time to `0`.  This appears to resolve the last problem of the dock appearing in `Always hide` or `Intelligently hide` mode during unlocking.

**Review by jacobgkau — APPROVED** [review]
Not seeing any more problems. Tested all dock preferences, workspace switching, and lock/unlocking with 1- and 2-display setups.

**Comment by pbui** [comment]
@jacobgkau Thanks for your patience and testing!

**Review by jackpot51 — APPROVED** [review]
